services:
  blockchain:
    image: trufflesuite/ganache
    container_name: local-blockchain
    ports:
      - "8545:8545"

  deployer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vault-deployer
    depends_on:
      blockchain:
        condition: service_started
    environment:
      HARDHAT_NETWORK: localhost
    volumes:
      - .:/app
    command: sh ./docker/entrypoint.sh
